### ISSUE TITLE
Example in the video no longer runs

### ISSUE THREAD

**Issue by ianxul** [rafaqz/CellularAutomataWeb.jl#43]
Hi! The example in the youtube video linked in the readme no longer works (even if copied exactly). It would be useful if there were an example on how to use this package.

**Comment by rafaqz** [comment]
Things have changed a lot since the video!

Probably the best option is to see the example at https://rafaqz.github.io/ModelParameters.jl/stable/interactmodels/ and use the same `Param` syntax in your rules. I'll put that link in the readme.

**Comment by rafaqz** [comment]
Ok sorry I hadn't realized how out of date the readme was. It should be more helpful now. Let me know if you get it working.

**Comment by ianxul** [comment]
Thanks!

**Comment by rafaqz** [comment]
Also realised there were a few things broken in DynamicGrids that meant the sliders were  not actually doing anything during a simulation. The main problem with the interface is that it's difficult to test for problems like that.

Anyway, update to the latest version of everything in an hour or so and this should work for you. I'll work on keeping it that way too.
